version: '3'
services:
    manager-nginx:
        build:
            context: ./manager/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./manager:/app
        depends_on:
            - manager-php-fpm
            - manager-redis
            - mailer
        ports:
            - "8080:80"
    manager-php-fpm:
        build:
            context: ./manager/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./manager:/app
            - composer:/root/.composer/cache
        depends_on:
            - manager-postgres
            - manager-redis
            - mailer
        environment:
            XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
            PHP_IDE_CONFIG: "serverName=docker"
            # for macOS IP 10.254.254.254
    manager-node:
        image: node:11.13-alpine
        volumes:
            - ./manager:/app
        working_dir: /app
        tty: true
    manager-postgres:
        image: postgres:11.2-alpine
        container_name: manager-postgres
        volumes:
            - manager-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"
    manager-redis:
        image: redis:3.0-alpine
        volumes:
            - manager-redis:/data
        command: redis-server --requirepass secret
    mailer:
        image: mailhog/mailhog
        ports:
            - "8081:8025"
            
volumes:
    manager-postgres:
    manager-redis:
    composer: