version: '3'
services:
    manager-nginx:
        build:
            context: ./manager/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./manager:/app
        depends_on:
            - manager-php-fpm
            - mailer
        ports:
            - "8080:80"
    manager-php-fpm:
        build:
            context: ./manager/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./manager:/app
            - composer:/root/.composer/cache
        depends_on:
            - manager-postgres
            - mailer
    manager-postgres:
        image: postgres:11.2-alpine
        container_name: manager-postgres
        volumes:
            - manager-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"
    mailer:
        image: mailhog/mailhog
        ports:
            - "8081:8025"
            
volumes:
    manager-postgres:
    composer: